[package]
name = "vpnbridge-windows-tun"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vpnbridge-core = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util"] }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
